@startuml
skinparam ComponentBorderColor black
skinparam component {
	backgroundColor<<mvn>> Green
}

scale max 1024 width
scale max 800 height

node "Commons" as commons {
  [Ecipse Commons]
  [GExpression]
  [DSL]
  [Timeline]
}

node  "Simulation and Model Animation Framework" as simulation_model_animation{
  [Simulation and Model Animation]
}

node "Truffle Execution" as gemoc_truffle_execution{
  node  "Truffle Engine" as truffle_engine {
   	[Truffle Execution Core] <<mvn>>
  	[Truffle Execution UI]
  }
} 
 
node "GEMOC Framework" as gemoc_framework{
  [Execution Framework]
  [Framework Commons]
  [XDSML Framework]
} 

node  "Trace Framework" as trace {
  [Trace Commons]
  [Trace Generator]
  [Trace Manager]
}

node  "Java Execution" as java_execution {
  [Java XDSML]
  node "Java Engine" as java_engine{
  [Java Engine UI]
  [Java Engine Core] <<mvn>>
  }
}

node  "ALE Execution" as ale_execution {
  [ALE XDSML]<<not implemented yet>>
  [ALE Engine]
}
node  "MoccML Execution" as moccml_execution {
  [MOCCML XDSML]
  [MOCCML Engine]
}

commons <- simulation_model_animation
commons <- trace
simulation_model_animation <-- gemoc_framework
gemoc_framework -> trace
[XDSML Framework] <|.. [Java XDSML] 
[Execution Framework] <|.. java_engine
[Execution Framework] <|.. truffle_engine
[XDSML Framework] <|.. [ALE XDSML] 
[Execution Framework] <|.. [ALE Engine]
[XDSML Framework] <|.. [MOCCML XDSML] 
[Execution Framework] <|.. [MOCCML Engine]

@enduml